### PR TITLE
Add Cargo.lock

### PR DESCRIPTION
**Pull request by chenrui333**
I am about to create a homebrew formula for this tool, but meanwhile, I saw the `Cargo.lock` file is missing to prevent the reproducible build (https://github.com/Homebrew/homebrew-core/issues/46025), hence adding it into the repo.

### CODE REVIEW

**Review by simeg — APPROVED** [review]
Nice!

**Comment by simeg** [comment]
@chenrui333 Version 1.6.2 is released with the lock file included.

**Comment by chenrui333** [comment]
@simeg Thanks a lot, that is very fast turn-around. 😃

**Comment by chenrui333** [comment]
Looks like your release tag did not get updated.
https://github.com/simeg/eureka/releases

**Comment by simeg** [comment]
@chenrui333 Fixed it!

**Pull request merged**
